version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8002 caps_shop.wsgi --reload"
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8002:8002"
    depends_on:
      - postgres_db

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - postgres_db
      - web
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data: