# Generated by Django 3.2.8 on 2022-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='new_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
