# Generated by Django 3.2.8 on 2022-03-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='cap',
            new_name='caps',
        ),
    ]
