# Generated by Django 3.2.8 on 2022-01-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
