# Generated by Django 3.2.8 on 2022-03-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cap_events_caps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='new_price',
            new_name='ev_price',
        ),
    ]
