# Generated by Django 3.2.8 on 2022-01-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestsellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cap')),
            ],
        ),
    ]
