# Generated by Django 3.2.8 on 2022-03-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_new_price_events_ev_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='caps',
            new_name='cap',
        ),
    ]
