# Generated by Django 3.2.8 on 2022-03-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_caps_events_cap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bestsallers',
            new_name='Bestsaller',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
