# Generated by Django 3.2.8 on 2022-02-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bestsellers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bestsellers',
        ),
    ]
