# Generated by Django 3.2.8 on 2022-01-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bestsellers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bestsellers',
            new_name='Favorites',
        ),
    ]
