# Generated by Django 3.2.8 on 2022-03-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220310_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ev_price',
            new_name='event_price',
        ),
    ]
