# Generated by Django 3.2.8 on 2022-02-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_bestsellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='new_price',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
    ]
