# Generated by Django 3.2.8 on 2022-02-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cap_new_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cap',
            old_name='imege',
            new_name='image',
        ),
    ]
